---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: noctia-discordbot
  labels:
    app: noctia-discordbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noctia-discordbot
  template:
    metadata:
      labels:
        app: noctia-discordbot
    spec:
      containers:
      - name: python
        image: "${k8s.container.image}"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 512M
        env:
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: DISCORD_BOT_TOKEN
            value: "${discord.bot.token}"
          - name: DISCORD_TEST_GUILD
            value: "${discord.test.guild.id}"
          - name: DISCORD_MAIN_GUILD
            value: "${discord.main.guild.id}"
          - name: DB_USER
            value: "${db_user}"
          - name: DB_PASS
            value: "${db_pass}"
          - name: DB_HOST
            value: "${db_host}"
          - name: DB_PORT
            value: "${db_port}"
          - name: DB_NAME
            value: "${db_name}"
          - name: APP_DEBUG
            value: "${app_debug}"
      imagePullSecrets:
        - name: ${k8s.container.image.secret}
