CREATE TABLE `Entities` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uid` text DEFAULT NULL,
  `ent_type` text DEFAULT NULL,
  `name` text DEFAULT NULL,
  `surname` text DEFAULT NULL,
  `gender` text DEFAULT NULL,
  `race` text DEFAULT NULL,
  `height` int(11) DEFAULT NULL,
  `weight` int(11) DEFAULT NULL,
  `nsfw` int(11) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `backstory` text DEFAULT NULL,
  `char_role` text DEFAULT NULL,
  `char_level` int(11) DEFAULT 1,
  `role_level` int(11) DEFAULT 1,
  `mhp` int(11) DEFAULT 0,
  `mmp` int(11) DEFAULT 0,
  `msp` int(11) DEFAULT 0,
  `hp` int(11) DEFAULT 0,
  `mp` int(11) DEFAULT 0,
  `sp` int(11) DEFAULT 0,
  `ac` int(11) DEFAULT 10,
  `cur_exp` int(11) DEFAULT 0,
  `req_exp` int(11) DEFAULT 0,
  `raw_stats` text DEFAULT NULL,
  `stat_point` int(11) DEFAULT 0,
  `stats` text DEFAULT NULL,
  `skills` text DEFAULT NULL,
  `abilities` text DEFAULT NULL,
  `inventory` text DEFAULT NULL,
  `combat_ready` int(11) DEFAULT 1,
  PRIMARY KEY (`id`)
);